### ISSUE TITLE
AttributeError: module 'prettytable' has no attribute 'BOX_CHARS'

### ISSUE THREAD

**Issue by Whissi** [platomav/MCExtractor#11]
With the latest version, probably caused by commit 2cf669479b53908bef446ddb6b006e0b6fc988a5, I am getting
```
File (1/95): 06-03-02


Error: MCE just crashed, please report the following:

Traceback (most recent call last):
  File "MCE.py", line 1013, in <module>
    pt, pt_empty = mc_table(col_names, True, 1)
  File "MCE.py", line 727, in mc_table
    pt.set_style(prettytable.BOX_CHARS) # Comment out if UnicodeEncodeError
AttributeError: module 'prettytable' has no attribute 'BOX_CHARS'

```
When I remove the line 727, problem is gone.

**Comment by platomav** [comment]
Hello,

You have to re-install PTable dependency from my [fork](https://github.com/platomav/PTable/tree/boxchar) and it will work.

**Comment by platomav** [comment]
The instructions at the README explain that you need to download the zip source file from Github and install that via pip (pip3 install PTable-boxchar**.zip**).

I've been using Github Desktop for some time now and I don't see such option.
